Add .setSolidColor() for macOS
sindresorhus/wallpaper pull request #74
Opened 2021-05-25 23:49 UTC by codetheweb

Closes https://github.com/sindresorhus/wallpaper/issues/66

2021-05-26 06:30 UTC, sindresorhus requested changes

2021-05-26 06:30 UTC, sindresorhus commented on package.json
> +		"ava": "ava -s",
I prefer using the AVA config in package.json to set this instead of command-line flag.

2021-05-26 06:30 UTC, sindresorhus commented on index.d.ts
> +	__macOS only.__
```suggestion
	__macOS only__

```

2021-05-26 06:30 UTC, sindresorhus commented on readme.md
> +The color to set.
Should explicitly mention the color format.

2021-05-26 17:01 UTC, codetheweb commented
Thanks, should be good now.

2021-05-27 03:37 UTC, merged

2021-05-27 03:37 UTC, sindresorhus commented
Thanks :)

2021-05-27 03:38 UTC, sindresorhus commented
Interested in adding this to the CLI too? https://github.com/sindresorhus/wallpaper-cli

2021-05-27 23:41 UTC, codetheweb commented
Done 👍 

https://github.com/sindresorhus/wallpaper-cli/pull/9